version: '3'

services:
  nginx:
    image: feem/lemp-node-nginx
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "${DOCKER_MAP_PORT}:80"
    links:
      - laravel
      - nuxt
    depends_on:
      - nuxt
      - laravel

  nuxt:
    image: feem/lemp-node-nuxt
    expose:
      - 3000
    environment:
      - TZ=Asia/Tokyo
      - API_URL=${API_URL}

  laravel:
    image: feem/lemp-node-laravel
    expose:
      - 8000
    environment:
      - TZ=Asia/Tokyo
      - APP_URL=http://localhost:${DOCKER_MAP_PORT}
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=user_password
    links:
      - mysql

  mysql:
    image: mysql:5.7.28
    # command: bash -c 'usermod -o -u 1000 mysql; groupmod -o -g 500 mysql; chown -R mysql:root /var/run/mysqld/; /entrypoint.sh mysqld --user=mysql --console'
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
    # volumes:
    #  - ./mounts/my.cnf:/etc/mysql/conf.d/my.cnf
    #  - ./volumes/mysql:/var/lib/mysql
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
